# Change these first
owner: Wordnik # Your GitHub organization or username, where this repository lives
repo: wordnik-status # The name of this repository

sites:
  - name: Wordnik Community
    url: https://www.wordnik.com/community
  - name: Wordnik Developer
    url: https://developer.wordnik.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wordnik.com
  # baseUrl: /wordnik-status
  favicon: https://raw.githubusercontent.com/wordnik/status.wordnik.com/master/static/img/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/assets/favicon.png
  name: Wordnik Status
  introTitle: "Wordnik status: site and API"
  introMessage: Wordnik status checks, every 5 minutes. Need help? Email support@wordnik.com.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Donate
      href: https://www.wordnik.com/donate

